kind = "mobile"
previewPath = "/"
title = "Mi Bodega Personal"
version = "1.0.0"
id = "artifacts/mi-bodega"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22168

[services.development]
run = "pnpm --filter @workspace/mi-bodega run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/mi-bodega", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/mi-bodega", "run", "serve" ]

[services.env]
PORT = "22168"
BASE_PATH = "/"
